AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for ATPCO Lounge Access Lambda Function

Resources:
  AtpcoLoungeAccessLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: atpco-lounge-access-mcp-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DataZoneAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - datazone:ListDomains
                  - datazone:GetDomain
                  - datazone:ListProjects
                  - datazone:GetProject
                  - datazone:ListAssets
                  - datazone:GetAsset
                  - datazone:GetAssetType
                  - datazone:ListAssetRevisions
                  - datazone:GetAssetRevision
                  - datazone:SearchInventory
                  - datazone:Search
                  - datazone:GetDataSource
                  - datazone:ListDataSources
                Resource: "*"
              - Effect: Allow
                Action:
                  - glue:GetTable
                  - glue:GetTables
                  - glue:GetDatabase
                  - glue:GetDatabases
                  - glue:GetPartitions
                Resource: "*"

Outputs:
  LambdaRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt AtpcoLoungeAccessLambdaRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LambdaRoleArn"